package com.springplus.ssh.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Model class of 用户.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "user")
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id 主键. */
	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name ="id")
	private String id;

	/** 用户名. */
	@Column(name ="user_name")
	private String userName;

	/** 手机号码. */
	@Column(name ="mobile_number")
	private String mobileNumber;

	/** 邮箱. */
	@Column(name ="email")
	private String email;

	/** 密码. */
	@Column(name ="password")
	private String password;

	/** 用户类型. */
	@Column(name ="user_type")
	private Integer userType;

	/** 注册时间. */
	@Column(name ="register_time")
	private Date registerTime;

	/** 是否有效 0 有效 1 无效. */
	@Column(name ="validity")
	private String validity;

	/** 创建时间. */
	@Column(name ="create_date")
	private Date createDate;

	/** 更新时间. */
	@Column(name ="update_date")
	private Date updateDate;

	/** 备注信息. */
	@Column(name ="remarks")
	private String remarks;

	/** 删除标记. */
	@Column(name ="del_flag")
	private String delFlag;

	/**
	 * Constructor.
	 */
	public User() {
	}

	/**
	 * Set the id 主键.
	 * 
	 * @param id
	 *            id 主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the id 主键.
	 * 
	 * @return id 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param userName
	 *            用户名
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the 手机号码.
	 * 
	 * @param mobileNumber
	 *            手机号码
	 */
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	/**
	 * Get the 手机号码.
	 * 
	 * @return 手机号码
	 */
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 用户类型.
	 * 
	 * @param userType
	 *            用户类型
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * Get the 用户类型.
	 * 
	 * @return 用户类型
	 */
	public Integer getUserType() {
		return this.userType;
	}

	/**
	 * Set the 注册时间.
	 * 
	 * @param registerTime
	 *            注册时间
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * Get the 注册时间.
	 * 
	 * @return 注册时间
	 */
	public Date getRegisterTime() {
		return this.registerTime;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
