package com.springplus.ssm.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用户.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id 主键. */
	private String id;

	/** 租户编码. */
	private String tenantCode = " ";

	/** 用户名. */
	private String userName = " ";

	/** 手机号码. */
	private String mobileNumber = " ";

	/** 邮箱. */
	private String email = " ";

	/** 密码. */
	private String password = " ";

	/** 用户类型. */
	private Integer userType = 0;

	/** 注册时间. */
	private Date registerTime = new Date();

	/** 是否有效 0 有效 1 无效. */
	private Integer validity = 0;

	/** 创建时间. */
	private Date createDate = new Date();

	/** 更新时间. */
	private Date updateDate = new Date();

	/** 备注信息. */
	private String remarks = " ";

	/** 删除标记. */
	private String delFlag = "0";

	/**
	 * Constructor.
	 */
	public User() {
	}

	/**
	 * Set the id 主键.
	 * 
	 * @param id
	 *            id 主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the id 主键.
	 * 
	 * @return id 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 租户编码.
	 * 
	 * @param tenantCode
	 *            租户编码
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * Get the 租户编码.
	 * 
	 * @return 租户编码
	 */
	public String getTenantCode() {
		return this.tenantCode;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param userName
	 *            用户名
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the 手机号码.
	 * 
	 * @param mobileNumber
	 *            手机号码
	 */
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	/**
	 * Get the 手机号码.
	 * 
	 * @return 手机号码
	 */
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 用户类型.
	 * 
	 * @param userType
	 *            用户类型
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * Get the 用户类型.
	 * 
	 * @return 用户类型
	 */
	public Integer getUserType() {
		return this.userType;
	}

	/**
	 * Set the 注册时间.
	 * 
	 * @param registerTime
	 *            注册时间
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * Get the 注册时间.
	 * 
	 * @return 注册时间
	 */
	public Date getRegisterTime() {
		return this.registerTime;
	}

	/**
	 * Set the 是否有效 0 有效 1 无效.
	 * 
	 * @param validity
	 *            是否有效 0 有效 1 无效
	 */
	public void setValidity(Integer validity) {
		this.validity = validity;
	}

	/**
	 * Get the 是否有效 0 有效 1 无效.
	 * 
	 * @return 是否有效 0 有效 1 无效
	 */
	public Integer getValidity() {
		return this.validity;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
